version: '3.7'
volumes:
 wordpress:
  name: wordpress
  driver: local
  driver_opts:
   device: /home/nscarab/data/wordpress
   o: bind
   type: none
 mariadb:
  name: mariadb
  driver: local
  driver_opts:
   device: /home/nscarab/data/mariadb
   o: bind
   type: none
services:
 nginx:
  depends_on:
   - wordpress
  container_name: nginx_container
  build: ./requirements/nginx
  image: nginx
  ports:
   - 443:443
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - the_network
  restart: always
 mariadb:
  container_name: mariadb_container
  build:
   context: ./requirements/mariadb
   args:
    DB_NAME: ${WORDPRESS_DB_NAME}
    MYSQL_USER: ${WORDPRESS_DB_USER}
    MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  image: mariadb
  volumes:
   - mariadb:/var/lib/mysql
  environment:
   - DB_NAME=${WORDPRESS_DB_NAME}
   - MYSQL_USER=${WORDPRESS_DB_USER}
   - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  networks:
   - the_network
  restart: always
 wordpress:
  depends_on:
   - mariadb
  container_name: wordpress_container
  build:
   context: ./requirements/wordpress
   args:
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
  image: wordpress
  volumes:
   - wordpress:/var/www/wordpress
  environment:
   - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
   - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
   - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
   - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
  networks:
   - the_network
  restart: always

networks:
 the_network:
  name: the_network
